//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escc.Umbraco.PickupAndSendEmails.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Escc.Umbraco.PickupAndSendEmails.Tests.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-Sender: your@email.here
        ///X-Receiver: example@eastsussex.gov.uk
        ///MIME-Version: 1.0
        ///From: your@email.here
        ///To: example@eastsussex.gov.uk
        ///Date: 18 Dec 2017 16:54:57 +0000
        ///Subject: The Form &apos;Test form&apos; was submitted
        ///Content-Type: text/html; charset=us-ascii
        ///Content-Transfer-Encoding: quoted-printable
        ///
        ///=0D=0A&lt;!DOCTYPE html&gt;=0D=0A&lt;html&gt;=0D=0A&lt;head&gt;=0D=0A    &lt;title&gt;&lt;/t=
        ///itle&gt;=0D=0A    &lt;meta http-equiv=3D&quot;Content-Type&quot; content=3D&quot;text/=
        ///html; charset=3Dutf-8&quot; /&gt;=0D=0A    &lt;meta name=3D&quot;viewport&quot; conten=
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FormSubmittedEmail {
            get {
                return ResourceManager.GetString("FormSubmittedEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-Sender: your@email.here
        ///X-Receiver: example@eastsussex.gov.uk
        ///MIME-Version: 1.0
        ///From: your@email.here
        ///To: example@eastsussex.gov.uk
        ///Date: 20 Dec 2017 15:26:40 +0000
        ///Subject: The Form &apos;Report an incident or issue to Trading Standards (version
        /// 1 / 2017-12-20-current)&apos; was submitted
        ///Content-Type: text/html; charset=us-ascii
        ///Content-Transfer-Encoding: quoted-printable
        ///
        ///=0D=0A&lt;!DOCTYPE html&gt;=0D=0A&lt;html&gt;=0D=0A&lt;head&gt;=0D=0A    &lt;title&gt;&lt;/t=
        ///itle&gt;=0D=0A    &lt;meta http-equiv=3D&quot;Content-Type&quot; content=3D&quot;te [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FormSubmittedEmailMultilineSubject {
            get {
                return ResourceManager.GetString("FormSubmittedEmailMultilineSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-Sender: do-not-reply@eastsussex.gov.uk
        ///X-Receiver: john.smith@eastsussex.gov.uk
        ///X-Receiver: jane.doe@eastsussex.gov.uk
        ///X-Receiver: joe.bloggs@eastsussex.gov.uk
        ///MIME-Version: 1.0
        ///From: do-not-reply@eastsussex.gov.uk
        ///To: john.smith@eastsussex.gov.uk, jane.doe@eastsussex.gov.uk,
        /// joe.bloggs@eastsussex.gov.uk
        ///Date: 15 May 2018 15:32:42 +0000
        ///Subject: The Form &apos;Example form (v0001) used
        /// 2018-05-10 to current&apos; was submitted
        ///Content-Type: text/html; charset=us-ascii
        ///Content-Transfer-Encoding: quoted [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FormSubmittedEmailMultipleRecipients {
            get {
                return ResourceManager.GetString("FormSubmittedEmailMultipleRecipients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-Sender: do-not-reply@eastsussex.gov.uk
        ///X-Receiver: example@eastsussex.gov.uk
        ///MIME-Version: 1.0
        ///From: do-not-reply@eastsussex.gov.uk
        ///To: webstaff@eastsussex.gov.uk
        ///Date: 19 Dec 2017 10:16:02 +0000
        ///Subject: Umbraco: Reset Password
        ///Content-Type: text/html; charset=us-ascii
        ///Content-Transfer-Encoding: quoted-printable
        ///
        ///&lt;p&gt;Your username to login to the Umbraco back-office is: &lt;strong&gt;=
        ///example&lt;/strong&gt;&lt;/p&gt;&lt;p&gt;Click &lt;a href=3D&quot;https://hostname=
        ///..azurewebsites.net/umbraco/ValidatePasswordResetCode?u=3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PasswordResetEmail {
            get {
                return ResourceManager.GetString("PasswordResetEmail", resourceCulture);
            }
        }
    }
}
